Movie.destroy_all
Review.destroy_all

puts "🌱 Seeding spices..."
Movie.create(title: "Nobody", director: "Ilya Naishuller", genre: "Action",summary: "A docile family man slowly reveals his true character after his house gets burgled by two petty thieves, which, coincidentally, leads him going to a bloody war with a Russian crime boss." ,release_year: 2021)
Movie.create(title: "The Green Knight", director: "David Lowery",genre: "Adventure",summary: "A fantasy retelling of the medieval story of Sir Gawain and the Green Knight.",release_year:2021)
Movie.create(title: "The Hand of God", director: "Paolo Sorrentino" ,genre: "Drama",summary: "In 1980s Naples, young Fabietto pursues his love for football as family tragedy strikes, shaping his uncertain but promising future as a filmmaker.",release_year:2021)
Movie.create(title: "The French Dispatch" , director: "Wes Anderson",genre: "Dramedy",summary: "A love letter to journalists set in an outpost of an American newspaper in a fictional twentieth century French city that brings to life a collection of stories published in 'The French Dispatch Magazine'.",release_year:2021)
Movie.create(title: "The Last Duel", director: "Ridley Scott",genre: "Action" ,summary: "King Charles VI declares that Knight Jean de Carrouges settle his dispute with his squire by challenging him to a duel." ,release_year:2021)
Movie.create(title: "Dune", director: "Denis Villeneuve",genre: "Sci-Fi",summary: "Feature adaptation of Frank Herbert's science fiction novel about the son of a noble family entrusted with the protection of the most valuable asset and most vital element in the galaxy." ,release_year:2021)
Movie.create(title: "Last Night in Soho" , director: "Edgar Wright" ,genre: "Drama" ,summary: "An aspiring fashion designer is mysteriously able to enter the 1960s where she encounters a dazzling wannabe singer. But the glamour is not all it appears to be and the dreams of the past start to crack and splinter into something darker." ,release_year:2021)
Movie.create(title: "No Sudden Move", director: "Steven Soderbergh" ,genre: "Crime" ,summary: "A group of criminals are brought together under mysterious circumstances and have to work together to uncover what's really going on when their simple job goes completely sideways." ,release_year:2021)
Movie.create(title: "Pig", director: "Michael Sarnoski",genre: "Drama" ,summary: "A truffle hunter who lives alone in the Oregon wilderness must return to his past in Portland in search of his beloved foraging pig after she is kidnapped." ,release_year:2021)
Movie.create(title: "The Worst Person in the World" , director: "Joachim Trier" ,genre: "Comedy" ,summary: "The chronicles of four years in the life of Julie, a young woman who navigates the troubled waters of her love life and struggles to find her career path, leading her to take a realistic look at who she really is." ,release_year:2021)
Movie.create(title: "Licorice Pizza" , director: "Paul Thomas Anderson",genre: "Comedy",summary: "The story of Alana Kane and Gary Valentine growing up, running around and going through the treacherous navigation of first love in the San Fernando Valley, 1973." ,release_year:2021)

Review.create(title: "Violent fun", content: "I love this movie. You wouldn't expect him to be a good fit for a movie like this, but man it works. He feels like the everyday father, and the action scenes are still believable. Not only are they believable, but they're extremely well done. The violence feels real and visceral, and isn't overused (although I acknowledge that's a pretty subjective opinion). If you're a fan of movies like John Wick, you will enjoy this. It's obviously not as stylistic, but it has its own charm.", likes:5, movie_id: 1)
Review.create(title: "This film is myth", content: "Nothing in it is random, everything is important/symbolic, and things/people/events can represent more than one thing, simultaneously. Most criticism I've seen of the film comes from misguided expectations, or from not understanding it. ", likes:3, movie_id: 2)
Review.create(title: "Slow but wow", content: "I loved this film, despire being too slow and melancholic at times for my personal liking. The acting is out of this world and I believed every single character. Fabio's mother really looked and acted like his mother. Same for his brother. Everything felt authentic to the core.", likes:19, movie_id: 3)
Review.create(title: "Colorful delight", content: "My eyes hurt from trying to absorb all the visual stimuli that were so eloquently displayed before me for 107 min.
    First off, if you do not like Wes Anderson films, you can completely skip this trip.
    
    If you are interested in his work and the trailers tickle your fancy, there are better ways to initiate yourself into this world.
    This is like seeing a musical artist's greatest hits tour but not having discovered the fan-favorite album tracks where the magic really lies.", likes: 0, movie_id: 4)
Review.create(title: "Yay", content: "This is wonderful! Best historical/action film for a decade. A must see. Watch it in the cinema on the wide screen if you can, not at home on Netflix. Ridley Scott has long been the world's foremost film maker. A 21st century John Ford no less, though this film owes much to Anthony Mann's magnificent 'El Cid' (1962, Charlton Heston, Sophia Loren, John Fraser) and the lesser known Franklin J Schaffner's 'The Warlord' (1965, also with Charlton Heston).", likes:1, movie_id: 5)
Review.create(title: "Sci-fi at it's best", content: "A story and world that gave birth to fantasy and Sci-Fi as we know it, as a main influence and many more for years to come. Although, I haven’t seen the other adaptions of ‘Dune’ with either of the Lynch or TV version. So, this is my first introduction to the world and characters, and something that was once considered unadaptable has become a reality all thanks to Denis Villeneuve vision. And now I'm interested in this world and the movie leaves you wanting more.", likes:3, movie_id: 6)
Review.create(title: "Beautiful", content: "A couple weeks ago, watching this thriller is what makes me feel like the expected becomes the unexpected. It may even be my first ever thriller watch, what I like about it is possibly most of the music, fashion, and even being set in England of all places gives me quite the sensational British feel besides being a British civilian. ", likes:4, movie_id: 7)
Review.create(title: "Gangster movies are back", content: "If you understand the U.S. automotive history and love a good suspense movie with constant twists & turns then this movie is for you. If you want a story line spelled out for you play by play, then this movie is not for you and you will/can easily get lost. ", likes:3, movie_id: 8)
Review.create(title: "Shockingly emotional", content: "A deeper side of Nicholas Cage I would have never guessed. So much being said in such few words!! If you're on the fence about it, JUST DO IT! This movie will STILL have you thinking about it 3 days later lol. So many LAYERS and aspects, LOVED IT!! ", likes:2, movie_id: 9)
Review.create(title: "Best movie of the year!", content: "The title is the best fit for the Julie ( the leading role) , she is the worst person for her life and for other’s life. When you are watching the film , little by little you begin to feel the unstable personality of Julie and the consequences of being not satisfied with the things you have and always be adventurous about naive things in life . The directing was good especially when the movie became subjective and you empathized with the characters in a better way .", likes:0, movie_id: 10)
Review.create(title: "PTA doing PTA things", content: "Every so often, a movie comes along that exists in a state of nostalgic grace in that it manages to tug at heartstrings without being maudlin or treacly, and reminds you of that 'life is your oyster' feeling we all experienced while coming of age.", likes:9, movie_id: 11)

puts "✅ Done seeding!"